export const GET_CONTACTS = "GET_CONTACTS";
export const SET_ERRORS = "CONTACTS_ERROR";
export const ADD_CONTACT = "ADD_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const RESTORE_CONTACT = "RESTORE_CONTACT";
export const TRASH_CONTACT = "RESTORE_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const SEARCH_CONTACTS = "SEARCH_CONTACTS";
