export const GET_CONTACTS = "GET_UNTRASH_CONTACTS";
export const GET_TRASH_CONTACTS = "GET_UNTRASH_CONTACTS";
export const GET_CONTACT = "GET_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const SEARCH_CONTACT = "SEARCH_CONTACT";
